pg-calcula-dbbmf:
  image: postgres:10.6-alpine
  environment:
    POSTGRES_DB: calcula_bmf
    POSTGRES_USER: dbbmf
    POSTGRES_PASSWORD: dbbmf
  volumes:
    - /data/sql/calcula_bmf:/var/lib/postgresql/data
  ports:
    - "5433:5432"
