pg-calcula-dbbmf:
  image: postgres:10.6-alpine
  environment:
    POSTGRES_DB: calcula_bmf
    POSTGRES_USER: dbbmf
    POSTGRES_PASSWORD: dbbmf
  volumes:
    - /data/sql/:/docker-entrypoint-initdb.d/
  ports:
    - "5433:5432"

# Para CRIAR e INICIALIZAR os containers definidos acima:
# docker-compose up  (esse comando cria e inicia os containers. Caso não queira apendar o processo no console utilizar a opção -d)

# Para verificar os containers rodando:
# docker-compose ps

# Para PARAR os containers
# docker-compose stop

# Para PARAR E REMOVER os containers
# docker-compose down