-- DROP TABLE RECOMENDACAO_SEMANAL;
CREATE TABLE IF NOT EXISTS RECOMENDACAO_SEMANAL (
	ID_RECOMENDACAO BIGINT NOT NULL,
	CODNEG VARCHAR(255) NULL,
	DTPREGINI DATE NULL,
	DTPREGFIM DATE NULL,
	PRECO_FECHAMENTO DECIMAL(14,2) NULL,
	PRECO_MME12P DECIMAL(14,2) NULL,
	PRECO_MME26P DECIMAL(14,2) NULL,
	PRECO_MACD DECIMAL(14,2) NULL,
	PRECO_SINAL_MACD DECIMAL(14,2) NULL,
	PRECO_HISTOGRAMA DECIMAL(14,2) NULL,
	DECISAO VARCHAR(20) NULL
);

ALTER TABLE RECOMENDACAO_SEMANAL ADD PRIMARY KEY (CODNEG, DTPREGINI);

CREATE SEQUENCE RECOMENDACAO_SEMANAL_SEQ START 1;
