-- DROP TABLE MACD;
CREATE TABLE IF NOT EXISTS SINAL_MACD_SEMANAL (
	ID_SINAL_MACD BIGINT NOT NULL,
	CODNEG VARCHAR(255) NULL,
  DTPREGINI DATE NULL,
  DTPREGFIM DATE NULL,
	PRESINAL DECIMAL(14,2) NULL
);

ALTER TABLE SINAL_MACD_SEMANAL ADD PRIMARY KEY (CODNEG, DTPREGINI, DTPREGFIM);

CREATE SEQUENCE SINAL_MACD_SEMANAL_SEQ START 1;
