-- DROP TABLE AGENDA_ATIVO;
CREATE TABLE IF NOT EXISTS AGENDA_ATIVO (
	ID_AGENDA BIGINT NOT NULL,
	ID_ATIVO BIGINT NOT NULL
);

ALTER TABLE AGENDA_ATIVO ADD PRIMARY KEY (ID_AGENDA, ID_ATIVO);

CREATE SEQUENCE AGENDA_ATIVO_SEQ	START 1;

