-- DROP TABLE AGENDA_EXECUCAO;
CREATE TABLE IF NOT EXISTS AGENDA_EXECUCAO (
	ID_AGENDA BIGINT NOT NULL,
	NOME_USUARIO VARCHAR(255) NULL,
  DT_EXECUCAO DATE NOT NULL
);

ALTER TABLE AGENDA_EXECUCAO ADD PRIMARY KEY (ID_AGENDA);

CREATE SEQUENCE AGENDA_EXECUCAO_SEQ	START 1;

