ALTER TABLE CANDLESTICK_SEMANAL DROP COLUMN MEDIA_MOVEL_GERADA;
ALTER TABLE CANDLESTICK_SEMANAL DROP COLUMN MEDIA_EXPONECIAL_GERADA;
ALTER TABLE CANDLESTICK_SEMANAL DROP COLUMN MACD_GERADA;
ALTER TABLE CANDLESTICK_SEMANAL DROP COLUMN SINAL_MACD_GERADA;
ALTER TABLE CANDLESTICK_SEMANAL DROP COLUMN HISTOGRAMA_GERADA;