-- DROP TABLE USUARIO_ATIVO;
CREATE TABLE IF NOT EXISTS USUARIO_ATIVO (
  ID_ATIVO BIGINT NOT NULL,
  ID_USUARIO BIGINT NOT NULL
);

ALTER TABLE USUARIO_ATIVO ADD PRIMARY KEY (ID_USUARIO, ID_ATIVO);

ALTER TABLE USUARIO_ATIVO ADD CONSTRAINT FK_USUARIO_ATIVO
    FOREIGN KEY (ID_USUARIO)
    REFERENCES USUARIO (ID_USUARIO);



