ALTER TABLE CANDLESTICK_DIARIO DROP COLUMN MEDIA_MOVEL_GERADA;
ALTER TABLE CANDLESTICK_DIARIO DROP COLUMN MEDIA_EXPONECIAL_GERADA;
ALTER TABLE CANDLESTICK_DIARIO DROP COLUMN MACD_GERADA;
ALTER TABLE CANDLESTICK_DIARIO DROP COLUMN SINAL_MACD_GERADA;
ALTER TABLE CANDLESTICK_DIARIO DROP COLUMN HISTOGRAMA_GERADA;