server:
  port: 8667

#Swagger
swagger:
  enabled: true

management:
  context-path: /

# Spring properties
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/calcula_bmf
    username: dbbmf
    password: dbbmf
    driver-class-name: org.postgresql.Driver
  profiles:
    active: local
  application:
    name: calcula-cotacoes
  flyway:
    url: ${spring.datasource.url}
    enabled: true
    checkLocation: false
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    baseline-on-migrate: false
    schemas: 'public'
  kafka:
    auto-offset-reset: earliest
    properties.max.request.size: 15728640
    enable.auto.commit: false
    max.poll.records: 10
    key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
    bootstrap:
      servers: localhost:9092
    consumer:
      group-id: bmf
  jackson:
    serialization:
      write-dates-as-timestamps: false