server:
  port: 8667

#Swagger
swagger:
  enabled: true

management:
  context-path: /

# Spring properties
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/calcula_bmf
    username: dbbmf
    password: dbbmf
    driver-class-name: org.postgresql.Driver
  profiles:
    active: local
  application:
    name: calcula-cotacoes
  flyway:
    url: ${spring.datasource.url}
    enabled: true
    checkLocation: false
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    baseline-on-migrate: false
    schemas: 'public'
  kafka:
    auto-offset-reset: earliest
    properties.max.request.size: 15728640
    enable.auto.commit: false
    max.poll.records: 10
    key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
    bootstrap:
      servers: localhost:9092
    consumer:
      group-id: bmf
    concurrency: 10
    polltimeout: 3000
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: secret
    virtual-host: personal
  jackson:
    serialization:
      write-dates-as-timestamps: false

personal:
  rabbit:
    config:
      initialInterval: 5
      maxInterval: 5
      multiplier: 1
      retries: 1
      successConsumers: 1
      errorConsumers: 1
    bindings:
      -
        topic: recomendacao.diario.calcula
        routing-key: recomendacao.diario.calcula.input.rk
        queue: recomendacao.diario.calcula.input
      -
        topic: recomendacao.semanal.calcula
        routing-key: recomendacao.semanal.calcula.rk
        queue: recomendacao.semanal.calcula.input