-- DROP TABLE RECOMENDACAO;
CREATE TABLE IF NOT EXISTS RECOMENDACAO_DIARIO (
	ID_RECOMENDACAO BIGINT NOT NULL,
	CODNEG VARCHAR(255) NULL,
	DTPREG DATE NULL,
	PRECO_FECHAMENTO DECIMAL(14,2) NULL,
	PRECO_MME12P DECIMAL(14,2) NULL,
	PRECO_MME26P DECIMAL(14,2) NULL,
	PRECO_MACD DECIMAL(14,2) NULL,
	PRECO_SINAL_MACD DECIMAL(14,2) NULL,
	PRECO_HISTOGRAMA DECIMAL(14,2) NULL,
	DECISAO VARCHAR(20) NULL
);

ALTER TABLE RECOMENDACAO_DIARIO ADD PRIMARY KEY (CODNEG, DTPREG);

CREATE SEQUENCE RECOMENDACAO_DIARIO_SEQ START 1;
