-- DROP TABLE MACD;
CREATE TABLE IF NOT EXISTS MACD_SEMANAL (
	ID_MACD BIGINT NOT NULL,
	CODNEG VARCHAR(255) NULL,
	DTPREGINI DATE NULL,
  DTPREGFIM DATE NULL,
	PREMACD DECIMAL(14,2) NULL
);

ALTER TABLE MACD_SEMANAL ADD PRIMARY KEY (CODNEG, DTPREGINI, DTPREGFIM);

CREATE SEQUENCE MACD_SEMANAL_SEQ START 1;
