-- DROP TABLE CANDLESTICK_DIARIO;
CREATE TABLE IF NOT EXISTS CANDLESTICK_DIARIO (
	ID_CANDLE_DIARIO BIGINT NOT NULL,
	CODNEG VARCHAR(255) NULL,
	DTPREG DATE NULL,
	MEDIA_MOVEL_GERADA BOOLEAN NULL,
	MEDIA_EXPONECIAL_GERADA BOOLEAN NULL,
	MACD_GERADA BOOLEAN NULL,
	SINAL_MACD_GERADA BOOLEAN NULL,
	HISTOGRAMA_GERADA BOOLEAN NULL,
	PREABE DECIMAL(14,2) NULL,
	PREMAX DECIMAL(14,2) NULL,
	PREMIN DECIMAL(14,2) NULL,
	PREULT DECIMAL(14,2) NULL,
	SEMANA BIGINT NULL,
	VOLTOT DECIMAL(20,2) NULL
);

ALTER TABLE CANDLESTICK_DIARIO ADD PRIMARY KEY (CODNEG, DTPREG);

CREATE SEQUENCE CANDLESTICK_SEQ START 1;
