-- DROP TABLE HISTOGRAMA;
CREATE TABLE IF NOT EXISTS HISTOGRAMA_SEMANAL (
	ID_HISTOGRAMA BIGINT NOT NULL,
	CODNEG VARCHAR(255) NULL,
  DTPREGINI DATE NULL,
  DTPREGFIM DATE NULL,
	PREHIST DECIMAL(14,2) NULL
);

ALTER TABLE HISTOGRAMA_SEMANAL ADD PRIMARY KEY (CODNEG, DTPREGINI, DTPREGFIM);

CREATE SEQUENCE HISTOGRAMA_SEMANAL_SEQ START 1;
