-- DROP TABLE CONTROLE_EXECUCAO;
CREATE TABLE IF NOT EXISTS CONTROLE_EXECUCAO (
  ID_CONTROLE_EXECUCAO BIGINT NOT NULL,
  CONTROLE_EXECUCAO_ATIVO BOOLEAN NOT NULL,
  CALC_MEDIA_MOVEL_DIARIO_EXECUTADO BOOLEAN NULL,
  CALC_MEDIA_MOVEL_DIARIO_EXECUTADO_DTEXEC DATE NULL,
  CALC_MEDIA_MOVEL_SEMANAL_EXECUTADO BOOLEAN NULL,
  CALC_MEDIA_MOVEL_SEMANAL_EXECUTADO_DTEXEC DATE NULL,
  CALC_MEDIA_EXPONECIAL_DIARIO_EXECUTADO BOOLEAN NULL,
  CALC_MEDIA_EXPONECIAL_DIARIO_EXECUTADO_DTEXEC DATE NULL,
  CALC_MEDIA_EXPONECIAL_SEMANAL_EXECUTADO BOOLEAN NULL,
  CALC_MEDIA_EXPONECIAL_SEMANAL_EXECUTADO_DTEXEC DATE NULL,
  CALC_MACD_DIARIO_EXECUTADO BOOLEAN NULL,
  CALC_MACD_DIARIO_EXECUTADO_DTEXEC DATE NULL,
  CALC_MACD_SEMANAL_EXECUTADO BOOLEAN NULL,
  CALC_MACD_SEMANAL_EXECUTADO_DTEXEC DATE NULL,
  CALC_SINAL_MACD_DIARIO_EXECUTADO BOOLEAN NULL,
  CALC_SINAL_MACD_DIARIO_EXECUTADO_DTEXEC DATE NULL,
  CALC_SINAL_MACD_SEMANAL_EXECUTADO BOOLEAN NULL,
  CALC_SINAL_MACD_SEMANAL_EXECUTADO_DTEXEC DATE NULL,
  CALC_HISTOGRAMA_DIARIO_EXECUTADO BOOLEAN NULL,
  CALC_HISTOGRAMA_DIARIO_EXECUTADO_DTEXEC DATE NULL,
  CALC_HISTOGRAMA_SEMANAL_EXECUTADO BOOLEAN NULL,
  CALC_HISTOGRAMA_SEMANAL_EXECUTADO_DTEXEC DATE NULL
);

ALTER TABLE CONTROLE_EXECUCAO ADD PRIMARY KEY (ID_CONTROLE_EXECUCAO, CONTROLE_EXECUCAO_ATIVO);

insert into controle_execucao (
	id_controle_execucao,
	controle_execucao_ativo,
	calc_media_movel_diario_executado,
	calc_media_movel_diario_executado_dtexec,
	calc_media_movel_semanal_executado,
	calc_media_movel_semanal_executado_dtexec,
	calc_media_exponecial_diario_executado,
	calc_media_exponecial_diario_executado_dtexec,
	calc_media_exponecial_semanal_executado,
	calc_media_exponecial_semanal_executado_dtexec,
	calc_macd_diario_executado,
	calc_macd_diario_executado_dtexec,
	calc_macd_semanal_executado,
	calc_macd_semanal_executado_dtexec,
	calc_sinal_macd_diario_executado,
	calc_sinal_macd_diario_executado_dtexec,
	calc_sinal_macd_semanal_executado,
	calc_sinal_macd_semanal_executado_dtexec,
	calc_histograma_diario_executado,
	calc_histograma_diario_executado_dtexec,
	calc_histograma_semanal_executado,
	calc_histograma_semanal_executado_dtexec
) values (
	1,
	true,
	true,
	'2001-01-01',
	true,
	'2001-01-01',
	true,
	'2001-01-01',
	true,
	'2001-01-01',
	true,
	'2001-01-01',
	true,
	'2001-01-01',
	true,
	'2001-01-01',
	true,
	'2001-01-01',
	true,
	'2001-01-01',
	true,
	'2001-01-01'
);
