ALTER TABLE CANDLESTICK_SEMANAL DROP COLUMN IF EXISTS MEDIA_MOVEL_GERADA;
ALTER TABLE CANDLESTICK_SEMANAL DROP COLUMN IF EXISTS MEDIA_EXPONECIAL_GERADA;
ALTER TABLE CANDLESTICK_SEMANAL DROP COLUMN IF EXISTS MACD_GERADA;
ALTER TABLE CANDLESTICK_SEMANAL DROP COLUMN IF EXISTS SINAL_MACD_GERADA;
ALTER TABLE CANDLESTICK_SEMANAL DROP COLUMN IF EXISTS HISTOGRAMA_GERADA;