ALTER TABLE MEDIA_MOVEL_SIMPLES_SEMANAL ADD PRIMARY KEY (CODNEG, DTPREGINI, PERIODO);

ALTER TABLE MEDIA_MOVEL_EXPONENCIAL_SEMANAL ADD PRIMARY KEY (CODNEG, DTPREGINI, PERIODO);

ALTER TABLE MACD_SEMANAL ADD PRIMARY KEY (CODNEG, DTPREGINI);

ALTER TABLE SINAL_MACD_SEMANAL ADD PRIMARY KEY (CODNEG, DTPREGINI);

ALTER TABLE HISTOGRAMA_SEMANAL ADD PRIMARY KEY (CODNEG, DTPREGINI);
