-- DROP TABLE CANDLESTICK_SEMANAL;
CREATE TABLE IF NOT EXISTS CANDLESTICK_SEMANAL (
	ID_CANDLE_SEMANAL BIGINT NOT NULL,
	CODNEG VARCHAR(255) NULL,
	DTPREGINI DATE NULL,
	DTPREGFIM DATE NULL,
  MEDIA_MOVEL_GERADA BOOLEAN NULL,
  MEDIA_EXPONECIAL_GERADA BOOLEAN NULL,
  MACD_GERADA BOOLEAN NULL,
  SINAL_MACD_GERADA BOOLEAN NULL,
  HISTOGRAMA_GERADA BOOLEAN NULL,
	PREABE DECIMAL(14,2) NULL,
	PREMAX DECIMAL(14,2) NULL,
	PREMIN DECIMAL(14,2) NULL,
	PREULT DECIMAL(14,2) NULL,
	SEMANA INTEGER NULL,
	VOLTOT DECIMAL(20,2) NULL
);

ALTER TABLE CANDLESTICK_SEMANAL ADD PRIMARY KEY (CODNEG, DTPREGINI, DTPREGFIM);

CREATE SEQUENCE CANDLESTICK_SEMANAL_SEQ	START 1;

