ALTER TABLE MEDIA_MOVEL_SIMPLES_SEMANAL DROP CONSTRAINT IF EXISTS MEDIA_MOVEL_SIMPLES_SEMANAL_PKEY;
ALTER TABLE MEDIA_MOVEL_EXPONENCIAL_SEMANAL DROP CONSTRAINT IF EXISTS MEDIA_MOVEL_EXPONENCIAL_SEMANAL_PKEY;
ALTER TABLE MACD_SEMANAL DROP CONSTRAINT IF EXISTS MACD_SEMANAL_PKEY;
ALTER TABLE SINAL_MACD_SEMANAL DROP CONSTRAINT IF EXISTS SINAL_MACD_SEMANAL_PKEY;
ALTER TABLE HISTOGRAMA_SEMANAL DROP CONSTRAINT IF EXISTS HISTOGRAMA_SEMANAL_PKEY;
