ALTER TABLE RECOMENDACAO_SEMANAL ADD COLUMN PRECO_ABERTURA DECIMAL(14,2) NULL;
ALTER TABLE RECOMENDACAO_SEMANAL ADD COLUMN PRECO_MINIMO   DECIMAL(14,2) NULL;
ALTER TABLE RECOMENDACAO_SEMANAL ADD COLUMN PRECO_MAXIMO   DECIMAL(14,2) NULL;