-- DROP TABLE MEDIA_MOVEL_EXPONENCIAL;
CREATE TABLE MEDIA_MOVEL_EXPONENCIAL_DIARIO (
	ID_MEDIA_MOVEL_EXPONENCIAL BIGINT NOT NULL,
	CODNEG VARCHAR(255) NULL,
	DTPREG DATE NULL,
	PREMEDULT NUMERIC(14,2) NULL,
	PERIODO INTEGER NULL
);

ALTER TABLE MEDIA_MOVEL_EXPONENCIAL_DIARIO ADD PRIMARY KEY (CODNEG, DTPREG, PERIODO);

CREATE SEQUENCE MEDIA_MOVEL_EXPONENCIAL_DIARIO_SEQ START 1;
