-- DROP TABLE MACD;
CREATE TABLE IF NOT EXISTS SINAL_MACD_DIARIO (
	ID_SINAL_MACD BIGINT NOT NULL,
	CODNEG VARCHAR(255) NULL,
	DTPREG DATE NULL,
	PRESINAL DECIMAL(14,2) NULL
);

ALTER TABLE SINAL_MACD_DIARIO ADD PRIMARY KEY (CODNEG, DTPREG);

CREATE SEQUENCE SINAL_MACD_DIARIO_SEQ START 1;
