-- DROP TABLE HISTOGRAMA;
CREATE TABLE IF NOT EXISTS HISTOGRAMA_DIARIO (
	ID_HISTOGRAMA BIGINT NOT NULL,
	CODNEG VARCHAR(255) NULL,
	DTPREG DATE NULL,
	PREHIST DECIMAL(14,2) NULL
);

ALTER TABLE HISTOGRAMA_DIARIO ADD PRIMARY KEY (CODNEG, DTPREG);

CREATE SEQUENCE HISTOGRAMA_DIARIO_SEQ START 1;
